# Configuration file of FAR training experiment

# ========== Cluster configuration ========== 
# ip address of the parameter server (need 1 GPU process)
ps_ip: localhost

# ip address of each worker:# of available gpus process on each gpu in this node
# Note that if we collocate ps and worker on same GPU, then we need to decrease this number of available processes on that GPU by 1
# E.g., master node has 4 available processes, then 1 for the ps, and worker should be set to: worker:3
worker_ips: 
    - localhost:[2] # worker_ip: [(# processes on gpu) for gpu in available_gpus]

exp_path: $HOME/amna/iFedScale/core

# Entry function of executor and aggregator under $exp_path
executor_entry: executor.py

aggregator_entry: aggregator.py

auth:
    ssh_user: ""
    ssh_private_key: ~/.ssh/id_rsa

# cmd to run before we can indeed run FAR (in order)
setup_commands:
    - source activate ifedscale
    - export DATA_PATH=$HOME/github/dataset/data
    #- export NCCL_SOCKET_IFNAME='enp94s0f0'         # Run "ifconfig" to ensure the right NIC for nccl if you have multiple NICs

# ========== Additional job configuration ========== 
# Default parameters are specified in argParser.py, wherein more description of the parameter can be found

job_conf: 
    - log_path: $HOME/amna/iFedScale/highnewenergy  # Path of log files
    - job_name: google_speech_testing # Generate logs under this folder: log_path/job_name/time_stamp
    - task: speech
    - total_worker: 10                # Number of participants per round, we use K=100 in our paper, large K will be much slower
    - data_set: google_speech                     # Dataset: openImg, google_speech, stackoverflow
    - data_dir: $DATA_PATH/google_speech    # Path of the dataset
    #- data_map_dir: $DATA_PATH/client_data_mapping             # Allocation of data to each client, turn to iid setting if not provided
    - device_conf_file: $DATA_PATH/device_info/client_device_capacity     # Path of the client trace
    - device_avail_file: $DATA_PATH/device_info/client_behave_trace
    - model: resnet34                            # Models: e.g., shufflenet_v2_x2_0, mobilenet_v2, resnet34, albert-base-v2
    - gradient_policy: yogi                 # {"fed-yogi", "fed-prox", "fed-avg"}, "fed-avg" by default
    - eval_interval: 5                     # How many rounds to run a testing on the testing set
    - epochs: 20                      # Number of rounds to run this training. We use 1000 in our paper, while it may converge w/ ~400 rounds
    - filter_less: 21                       # Remove clients w/ less than 21 samples
    - num_loaders: 4
    - yogi_eta: 3e-3 
    - yogi_tau: 1e-8
    - local_steps: 30
    - learning_rate: 0.05
    - batch_size: 20
    - test_bsz: 20
    - use_wandb: True
    - total_clients: 1000
    - partitioning : 0
    - filter_class_ratio : 0.1
    - sample_mode : 'random'
    - scal_val : 0.75       # EAFL parameter for reward function


